name: 'publish'

on: workflow_dispatch

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: '--bundles msi'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Kesomannen/gale
        uses: actions/checkout@v4
        with:
          repository: Kesomannen/gale
          ref: '1.3.0'
          path: gale

      - name: Replace strings
        run: |
          chmod +x replace.sh
          bash replace.sh

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: |
          cd gale
          npm install

      - name: Set version code
        run: |
          bash -c 'sed -i "s/\(\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+\)/\1+chs${{ github.run_number }}/" gale/src-tauri/tauri.conf.json'

      - uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          tagName: __VERSION__+chs${{ github.run_number }} # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "Release __VERSION__+chs${{ github.run_number }}"
          releaseDraft: true
          args: ${{ matrix.args }}
          projectPath: 'gale'

      - name: Replace latest.json's github link to ghproxy link
        run: bash -c "find . -type f -name 'latest.json' -exec sed -i 's|https://github.com|https://ghfast.top/https://github.com|g' {} +"

      - name: Update gale-latest.json to github gist
        uses: exuanbo/actions-deploy-gist@v1
        if: matrix.platform == 'windows-latest'
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 48ae7ddf5b7bd612ed2108b2f94b4eb9
          gist_description: Auto-updater endpoint for gale
          file_path: latest.json
          gist_file_name: gale-latest.json